# .air.toml configuration file for Air

# Basic settings
[build]
  # Specify the command to run when rebuilding the application
  cmd = "go build -o ./tmp/main ."
  # Name of the binary produced by the build command
  bin = "./tmp/main"
  # Delay before restarting the application after a file change (in milliseconds)
  delay = 1000
  # Stop on build failure
  stop_on_error = true
  # Directory to exclude from watching (e.g., vendor, temporary directories)
  exclude_dir = ["tmp", "vendor"]

# Watcher settings
[watcher]
  # Watch these directories for changes
  include = [
    "**/*.go",
    "**/*.tmpl",
    "**/*.html",
  ]
  # Exclude these directories or files from watching
  exclude = [
    "tmp",
    "vendor",
  ]

# Logger settings
[log]
  # Display timestamp in logs
  timestamp = true
  # Customize log color
  color = true

# Misc settings
[misc]
  # Specify the environment variables to pass to the application
  clean_on_exit = true
  kill_signal = "ctrl+c"
